version: '3.7'

services:
  database:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data


volumes:
  database-data: